ekf_filter_node:
  ros__parameters:
    frequency: 100.0

    sensor_timeout: 0.1

    two_d_mode: false

    publish_tf: true
    publish_acceleration: false

    map_frame: map              # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_link  # Defaults to "base_link" if unspecified
    world_frame: odom

    # odom0: imu/data
    # odom0_config: [false, false, false,
    #                true,  true,  true,
    #                false, false, false,
    #                false, false, true,
    #                true,  true,  true]
    # odom0_queue_size: 10
    # odom0_nodelay: false
    # odom0_differential: false
    # odom0_relative: false
    # odom0_pose_rejection_threshold: 5.0
    # odom0_twist_rejection_threshold: 1.0

    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
